sudo: false

language: rust

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev

os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - |
      if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

install:
  - |
      if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl; fi

before_script:
  # load travis-cargo
  - |
      pip install 'travis-cargo<0.2' --user &&
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=$HOME/.local/bin/:$PATH; fi
      if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$HOME/Library/Python/2.7/bin:$PATH; fi

script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo --only stable doc

after_success:
  - travis-cargo coveralls --no-sudo --verify

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""